spring.application.name: backend-core

spring.datasource.url=jdbc:postgresql://db:5432/logistics_db
spring.datasource.username=user_admin
spring.datasource.password=password_secure
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



